/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableOverviewImport } from './routes/table-overview'
import { Route as CandleSticksImport } from './routes/candle-sticks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TableOverviewRoute = TableOverviewImport.update({
  id: '/table-overview',
  path: '/table-overview',
  getParentRoute: () => rootRoute,
} as any)

const CandleSticksRoute = CandleSticksImport.update({
  id: '/candle-sticks',
  path: '/candle-sticks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/candle-sticks': {
      id: '/candle-sticks'
      path: '/candle-sticks'
      fullPath: '/candle-sticks'
      preLoaderRoute: typeof CandleSticksImport
      parentRoute: typeof rootRoute
    }
    '/table-overview': {
      id: '/table-overview'
      path: '/table-overview'
      fullPath: '/table-overview'
      preLoaderRoute: typeof TableOverviewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candle-sticks': typeof CandleSticksRoute
  '/table-overview': typeof TableOverviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candle-sticks': typeof CandleSticksRoute
  '/table-overview': typeof TableOverviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/candle-sticks': typeof CandleSticksRoute
  '/table-overview': typeof TableOverviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candle-sticks' | '/table-overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candle-sticks' | '/table-overview'
  id: '__root__' | '/' | '/candle-sticks' | '/table-overview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandleSticksRoute: typeof CandleSticksRoute
  TableOverviewRoute: typeof TableOverviewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandleSticksRoute: CandleSticksRoute,
  TableOverviewRoute: TableOverviewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/candle-sticks",
        "/table-overview"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/candle-sticks": {
      "filePath": "candle-sticks.tsx"
    },
    "/table-overview": {
      "filePath": "table-overview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
